name: 'Tests | Basic tests'

on: [push]

jobs:
  # A little modified official script for testing final archive
  # We use it regularly for checking if the project meets all requirements
  official-test-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIV_KEY }}

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 10
          platform: x64

      - name: We need gcc-10.2 but we have gcc-10 only...
        run: sudo ln -s /usr/bin/gcc-10 /usr/local/bin/gcc-10.2

      - name: Install packages for LaTeX (and BibTeX) compilation
        run: sudo apt install -y texlive texlive-plain-generic texlive-latex-extra texlive-lang-czechslovak texlive-lang-greek texlive-font-utils texlive-bibtex-extra

      - name: Run Make rule for creating final archive
        run: cd src; make archive

      - name: Create directory for testing purposes
        run: mkdir tmp

      - name: Prepare test script (apply patch with required modifications for Github Actions)
        run: cd test/basics; patch is_it_ok.sh is_it_ok.sh.patch

      - name: Run test script
        run: ./test/basics/is_it_ok.sh xsmahe01.tar.gz ./tmp

  # Check rules from assignment not tested by the official script
  other-assignment-rules:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIV_KEY }}

      - name: Install packages for LaTeX (and BibTeX) compilation
        run: sudo apt install -y texlive texlive-plain-generic texlive-latex-extra texlive-lang-czechslovak texlive-lang-greek texlive-font-utils texlive-bibtex-extra

      - name: Run Make rule for creating final archive
        run: cd src; make archive

      - name: Create directory for testing purposes
        run: mkdir tmp

      - name: Extract the archive to the previously prepared directory
        run: cd tmp; tar -xzvf ../xsmahe01.tar.gz

      - name: Run own tests
        run: ./test/basics/other-assignment-rules.sh
        env:
          EXTRA_CFLAGS: -Werror
