name: 'Automation | Issue'

on:
  issues:
    types: [assigned]

jobs:
  # Add pull request shortcut to project column
  set-as-in-progress:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: IFJ & IAL projekt
          column: In progress
          repo-token: ${{ secrets.PROJECT_AUTOMATION_TOKEN }}
