name: 'Tests | Unit tests'

on: [push]

jobs:
  # Automatically compile and run all of available unit tests
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Make rule for creating and running unit tests
        run: cd src; make test; ../test/unit/get-results.sh
